apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: muwc9cx2x-nodejs
  janus-idp.io/tekton: muwc9cx2x-nodejs
  backstage.io/kubernetes-id: muwc9cx2x-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: muwc9cx2x-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
