apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: muwc9cx2x-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: muwc9cx2x-nodejs 
  name: muwc9cx2x-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: muwc9cx2x-nodejs 
